# Generated by Django 4.2.4 on 2023-09-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='public_flg',
            field=models.BooleanField(default=False, verbose_name='признак публикации'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='story',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
